# Generated by Django 5.1.2 on 2024-10-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_comment_author_alter_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to='network.userprofile'),
        ),
    ]
