# Generated by Django 5.1.2 on 2024-10-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_sender_friendrequest_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
