# Generated by Django 5.1.2 on 2024-11-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
