# Generated by Django 5.1.2 on 2024-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_post_game_title'),
    ]

    operations = [
        
    ]
