# Generated by Django 5.1.2 on 2024-12-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_post_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views_count',
        )
    ]
