# Generated by Django 5.1.2 on 2024-12-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_remove_post_game_slug_remove_post_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
