# Generated by Django 5.1.2 on 2024-12-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_alter_userprofile_avatar'),
    ]

    operations = [
    ]
