# Generated by Django 5.1.2 on 2024-12-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_post_game_slug'),
    ]

    operations = [
    ]
