# Generated by Django 5.1.2 on 2024-12-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_rename_game_slug_post_game_slug2'),
    ]

    operations = [
    ]
