# Generated by Django 5.1.2 on 2024-12-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_post_game_slug2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game_title',
            field=models.CharField(blank=True, default='Unknown Game', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
