# Generated by Django 5.1.2 on 2024-12-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_alter_post_game_title_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
